typography_spectrum: 0.5465641874092456
color:
  saturation: 0.1604545388521977
  brandStrength: 0.6240910796027188
  rhythmicContrast: 0.5949636491717273
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
  lightness: 0.025748621393271748
github: true
opengraph:
  appId: '851579398255932'
layout_spectrum: 0.5444972349055075
author:
  email: kalostypi@icloud.com
  name: Learning Ways Hellas - Tomatis Hellas
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8722394b-fd91-4b5d-8ec9-6e76cfb8b0b9.gif
name: robotakiahellas.com
url: 'http://robotakiahellas.com'
navigation:
  - name: Τι είναι ρομποτική;
    id: 13188d35-36f5-402c-9d1c-ab08fd3e917d
    type: content
  - name: 'Εργαστήρια Bee-Bot®: για παιδιά 4-8 χρόνων'
    id: 4a2ea5c6-93ca-43c0-812e-595affce3bd0
    type: content
  - name: 'Εργαστήρια  ScratchJr: για παιδιά 4-12 χρόνων'
    id: fbb84d10-051b-4b68-b739-4f56ae550689
    type: content
  - name: “Δημιουργικά Σαββατοκύριακα”
    id: fba7f52f-4d40-4a30-a746-66a9ea62d897
    type: content
  - name: Πρόγραμμα Εργαστηρίων / Πάσχα 2017!
    id: d3fbc86f-0eb7-4576-97c0-79f514d17a76
    type: content
  - name: Γνωρίστε τα ROBOTάκια!
    id: b38e17a1-18fb-4728-a541-0ceb87e7db80
    type: content
  - name: Επικοινωνία
    id: 1b4f4339-bc8e-45b3-a285-a9079940d2fc
    type: content
  - name: GALLERY
    id: f5398015-5add-4ebe-8120-4fd7219b06c6
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0a49a115-3bc4-43bd-b763-df295b6a7909.gif
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ROBOTάκια   HELLAS
content: []
description: Early Learning Robotics
purpose:
  - type: contact
    url: 'mailto:hellasrobotakia@gmail.com'
    label: Contact ROBOTάκια
  - type: contact
    url: 'tel:2299112171'
    label: Call 2299112171
