typography_spectrum: 0.5011937356885928
color:
  saturation: 0.689229284473741
  brandStrength: 0.9081922724211385
  rhythmicContrast: 0.7336942338372701
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
  lightness: 0.43182290899447434
github: true
opengraph:
  appId: '@robotakiahellas'
layout_spectrum: 0.5471310605807691
author:
  email: kalostypi@icloud.com
  name: Learning Ways Hellas - Tomatis Hellas
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8722394b-fd91-4b5d-8ec9-6e76cfb8b0b9.gif
name: robotakiahellas.com
url: 'http://robotakiahellas.com'
navigation:
  - name: Τι είναι Ρομποτική;
    id: 13188d35-36f5-402c-9d1c-ab08fd3e917d
    type: content
  - name: Εργαστήρια Ρομποτικής για παιδιά
    id: b94b0846-86fa-491e-92ae-03eefe7fe98b
    type: content
  - name: Δημιουργική Μάθηση
    id: 74a5f10d-2b18-4408-85ee-fc4286cd5f4d
    type: content
  - name: 'Bee-Bot®: για παιδιά 4-8 χρόνων'
    id: 4a2ea5c6-93ca-43c0-812e-595affce3bd0
    type: content
  - name: Πρόγραμμα Bee-Bot®
    id: d3fbc86f-0eb7-4576-97c0-79f514d17a76
    type: content
  - name: Αιτήσεις Συμμετοχής ΒeeBot®
    url: >-
      http://www.tomatishellas.gr/bee-bot-introduction-robotics/bee-bot2016-%CE%B1%CE%AF%CF%84%CE%B7%CF%83%CE%B7-%CF%83%CF%85%CE%BC%CE%BC%CE%B5%CF%84%CE%BF%CF%87%CE%AE%CF%82-2/
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0a49a115-3bc4-43bd-b763-df295b6a7909.gif
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ROBOTάκια   HELLAS
content: []
description: Early Learning Robotics
