title: ROBOTάκια   HELLAS
content: []
github: true
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: Early Learning Robotics
color:
  saturation: 0.2328481288112257
  brandStrength: 0.1883987080713383
  rhythmicContrast: 0.2784374965731018
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
  lightness: 0.2374784666885355
navigation:
  - name: Τι είναι Ρομποτική;
    id: 13188d35-36f5-402c-9d1c-ab08fd3e917d
    type: content
  - name: Εργαστήρια Ρομποτικής για παιδιά
    id: b94b0846-86fa-491e-92ae-03eefe7fe98b
    type: content
  - name: Δημιουργική Μάθηση
    id: 74a5f10d-2b18-4408-85ee-fc4286cd5f4d
    type: content
  - name: Εργαστήρια Ρομποτικής Bee-Bot®
    id: 4a2ea5c6-93ca-43c0-812e-595affce3bd0
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0a49a115-3bc4-43bd-b763-df295b6a7909.gif
author:
  email: kalostypi@icloud.com
  name: Learning Ways Hellas - Tomatis Hellas
  url: ''
name: robotakiahellas.com
opengraph:
  appId: '@robotakiahellas'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8722394b-fd91-4b5d-8ec9-6e76cfb8b0b9.gif
typography_spectrum: 0.5059737
layout_spectrum: 0.3673835
url: 'http://robotakiahellas.com'
