typography_spectrum: 0.5465641874092456
color:
  saturation: 0.1604545388521977
  brandStrength: 0.6240910796027188
  rhythmicContrast: 0.5949636491717273
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
  lightness: 0.025748621393271748
github: true
opengraph:
  appId: '851579398255932'
layout_spectrum: 0.5444972349055075
author:
  email: kalostypi@icloud.com
  name: Learning Ways Hellas - Tomatis Hellas
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8722394b-fd91-4b5d-8ec9-6e76cfb8b0b9.gif
name: robotakiahellas.com
url: 'http://robotakiahellas.com'
navigation:
  - name: Εκπαιδευτική Ρομποτική
    id: fba7f52f-4d40-4a30-a746-66a9ea62d897
    type: content
  - name: Τι είναι Ρομποτική;
    id: 13188d35-36f5-402c-9d1c-ab08fd3e917d
    type: content
  - name: Εργαστήρια Ρομποτικής για παιδιά 4 -11
    id: b94b0846-86fa-491e-92ae-03eefe7fe98b
    type: content
  - name: Επιστημονική Γνώση
    id: 74a5f10d-2b18-4408-85ee-fc4286cd5f4d
    type: content
  - name: Εργαστήρια Bee-Bot®
    id: 4a2ea5c6-93ca-43c0-812e-595affce3bd0
    type: content
  - name: Γνωρίστε τα ROBOTάκια μας!
    id: b38e17a1-18fb-4728-a541-0ceb87e7db80
    type: content
  - name: Επικοινωνία
    id: 1b4f4339-bc8e-45b3-a285-a9079940d2fc
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0a49a115-3bc4-43bd-b763-df295b6a7909.gif
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ROBOTάκια   HELLAS
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FPmqWjOcNw8k%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DPmqWjOcNw8k&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FPmqWjOcNw8k%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen="true"></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      datePublished: null
      isBasedOnUrl: 'https://youtu.be/PmqWjOcNw8k'
      keywords:
        - ''
      related: []
      author:
        - name: Robo Wunderkind
          url: 'https://www.youtube.com/channel/UCIdr8baf1aeALXTyQumYIaQ'
          avatar: {}
      '@context': 'http://schema.org'
      title: Getting started with Robo Wunderkind
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=PmqWjOcNw8k&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=PmqWjOcNw8k&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=PmqWjOcNw8k&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=PmqWjOcNw8k&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=PmqWjOcNw8k&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=PmqWjOcNw8k'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=PmqWjOcNw8k
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=PmqWjOcNw8k
          package: '544007664'
          namespace: google
          type: ios
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: youtu.be
      description: >-
        First steps to do while getting to know your Robo Wunderkind kit. If you
        need further help with the firmware update, please see this:
        http://www.robowunderkind.com/firmware-update Find the help on getting
        started on our website: http://www.robowunderkind.com/getting-started/
        Find our apps in the Apple App Store and Google Play Store: Robo Code
        and Robo Live.
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Early Learning Robotics
purpose:
  - type: contact
    url: 'mailto:hellasrobotakia@gmail.com'
    label: Contact ROBOTάκια
  - type: contact
    url: 'tel:2299112171'
    label: Call 2299112171
